### ISSUE TITLE
V3.0.0 to be released the weekend of June 6th

### ISSUE THREAD

**Issue by chanan** [chanan/BlazorStyled#86]
Some breaking changes are coming in the next version. This only matters if you use the API. If you are using the `<Styled>` nothing changes

- *Global Styles:* Set and Get global styles signature is changing
- Almost all methods will become async

**Update:**

As of 3.0.0-alpha-04, all functions have both sync and async versions, thus not breaking backward compatibility. 

For example, `IStyled.Css` and `IStyled.CssAsync`

**Comment by VR-Architect** [comment]
I upgraded to v3a2 from v2.5a1 and have error in browser window. If I role back to v2.5 code works. I am only using <styled>

```
blazor.server.js:15 [2020-04-14T13:51:05.295Z] Error: BlazorStyled.StyledException: CSS Parse Error
.ControlNavBar .toplevel { color: #0366d6; font-family: Arial, Helvetica, 'sans-serif'; } .ControlNavBar .toplevel:hover { color: rgba(0,0,0,.5); font-size: 14px; } .ControlNavBar .navbar { color: #0366d6; font-size: 14px; background-color: #f8f9fa; border-width: 0px; border-radius: 0px; border-color: #808080; border-style: solid; } .ControlNavBar .searchBox { border-width: 1px; border-color: #ced4da; background-color: #fff; color: #28a745; } .ControlNavBar .searchBtn { border-width: 1px; border-color: #28a745; background-color: transparent; color: #28a745; } .ControlNavBar .hamburger { color: rgba(0,0,0,.5); border-color: rgba(0,0,0,.1); font-size: 34px; border-width: 1px; border-radius: 5px; background-color: #f8f9fa; } .ControlNavBar .nav-item:hover { background-color: ##d0d0d0; border-width: 1px; border-radius: 10px; border-color: #808080; border-style: solid; } .ControlNavBar .hover-gradient:hover { background: linear-gradient(to bottom, #ffff20 0%, ##d0d0d0 100%); background: -webkit-linear-gradient(top, #ffff20 0%, ##d0d0d0 100%); border-width: 1px; border-radius: 10px; border-color: #808080; border-style: solid; }
 ---> Microsoft.JSInterop.JSException: Unexpected identifier
SyntaxError: Unexpected identifier
    at eval (<anonymous>)
    at https://localhost:44382/_framework/blazor.server.js:8:31421
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (https://localhost:44382/_framework/blazor.server.js:8:31390)
    at https://localhost:44382/_framework/blazor.server.js:1:19202
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (https://localhost:44382/_framework/blazor.server.js:1:19173)
    at e.processIncomingData (https://localhost:44382/_framework/blazor.server.js:1:17165)
    at e.connection.onreceive (https://localhost:44382/_framework/blazor.server.js:1:10276)
    at WebSocket.i.onmessage (https://localhost:44382/_framework/blazor.server.js:1:38091)
   at Microsoft.JSInterop.JSRuntime.InvokeWithDefaultCancellation[T](String identifier, Object[] args)
   at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
   at BlazorStyled.Internal.ScriptManager.Init()
   at BlazorStyled.Internal.ScriptManager.UpdatedParsedClasses(String stylesheetId, String stylesheetName, Int32 priority, IList`1 parsedClasses)
   at BlazorStyled.Internal.StyledImpl.Css(String className, String css)
   --- End of inner exception stack trace ---
   at BlazorStyled.Internal.StyledImpl.Css(String className, String css)
   at BlazorStyled.Styled.ProcessParameters()
   at BlazorStyled.Styled.OnParametersSetAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
e.log @ blazor.server.js:15
4blazor.server.js:1 Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State.
    at e.send (blazor.server.js:1)
    at e.sendMessage (blazor.server.js:1)
    at e.sendWithProtocol (blazor.server.js:1)
    at e.send (blazor.server.js:1)
    at blazor.server.js:8
    at Object.t.dispatchEvent (blazor.server.js:8)
    at blazor.server.js:8
    at e.onEvent (blazor.server.js:8)
    at e.onGlobalEvent (blazor.server.js:8)
blazor.server.js:1 Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State.
    at e.send (blazor.server.js:1)
    at e.sendMessage (blazor.server.js:1)
    at e.sendWithProtocol (blazor.server.js:1)
    at e.send (blazor.server.js:1)
    at blazor.server.js:8
    at Object.t.dispatchEvent (blazor.server.js:8)
    at blazor.server.js:8
    at e.onEvent (blazor.server.js:8)
    at e.onGlobalEvent (blazor.server.js:8)
e.send @ blazor.server.js:1
e.sendMessage @ blazor.server.js:1
e.sendWithProtocol @ blazor.server.js:1
e.send @ blazor.server.js:1
(anonymous) @ blazor.server.js:8
t.dispatchEvent @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
(anonymous) @ blazor.server.js:8
e.onGlobalEvent @ blazor.server.js:8
```


```
<Styled>
    .ControlNavBar .toplevel {
    color: @props.GeneralFontColor.Color1;
    font-family: @props.GeneralFontName1, @props.GeneralFontName2, @props.GeneralFontName3;
    }
    .ControlNavBar .toplevel:hover {
    color: @props.HoverFontColor.Color1;
    font-size: @HoverFontSize;
    }

    .ControlNavBar .navbar {
    color: @props.GeneralFontColor.Color1;
    font-size: @GeneralFontSize;
    background-color: @props.GeneralBgColor.Color1;
    border-width: @GeneralBorderWidth;
    border-radius: @GeneralBorderRadius;
    border-color: @props.GeneralBorderColor.Color1;
    border-style: @props.GeneralBorderStyle;
    }

    .ControlNavBar .searchBox {
    border-width: @SearchBoxBorderWidth;
    border-color: @props.SearchBoxBorderColor.Color1;
    background-color: @props.SearchBoxBgColor.Color1;
    color: @props.SearchBtnFontColor.Color1;
    }

    .ControlNavBar .searchBtn {
    border-width: @SearchBtnBorderWidth;
    border-color: @props.SearchBtnBorderColor.Color1;
    background-color: @props.SearchBtnBgColor.Color1;
    color: @props.SearchBtnFontColor.Color1;
    }

    .ControlNavBar .hamburger {
    color: @props.CollapseFontColor.Color1;
    border-color: @props.CollapseBorderColor.Color1;
    font-size: @CollapseFontSize;
    border-width: @CollapseBorderWidth;
    border-radius: @CollapseBorderRadius;
    background-color: @props.CollapseBgColor.Color1;
    }

    @* The order of these two hovers matters! Scott *@
    .ControlNavBar .nav-item:hover {
    background-color: @props.HoverBgColor.Color1;
    border-width: @HoverBorderWidth;
    border-radius: @HoverBorderRadius;
    border-color: @props.HoverBorderColor.Color1;
    border-style: @props.HoverBorderStyle;
    }
    .ControlNavBar .hover-gradient:hover {
    background: linear-gradient(to bottom, @props.HoverBgColor.Color2 0%, @props.HoverBgColor.Color1 100%);
    background: -webkit-linear-gradient(top, @props.HoverBgColor.Color2 0%, @props.HoverBgColor.Color1 100%);
    border-width: @HoverBorderWidth;
    border-radius: @HoverBorderRadius;
    border-color: @props.HoverBorderColor.Color1;
    border-style: @props.HoverBorderStyle;
    }
</Styled>
```

**Comment by chanan** [comment]
The alpha v2 version does not have the full functionality working yet.

Your best bet is to stay on the released version for now. If you really want to try it out, I can make a new version (alpha-03) that has the full set of functionality, but be aware if you use lots of theme variables (SetThemeValue) it will be slow.

**Comment by VR-Architect** [comment]
I can wait. Just wanted you to know :)

If you need a tester with real project, please let me know.

**Comment by chanan** [comment]
I will! When I have a real one that fully works and is not slow I will post it! I just got everything working (again) last night, that's when I noticed it was slow (weirdly only on CSB, not on SSB). Haven't figured out yet how to find where the slowness occurs (Although I suspect it has to do with the way it does Themes now as well as I think it is re-adding the same CSS rules multiple times) - So haven't figured out yet how to fix it. But, at least every operation works again! So shouldn't be long now... hopefully...

**Comment by chanan** [comment]
@VR-Architect if you want to try V3.0 here is a slightly better version: https://github.com/chanan/BlazorStyled/releases/tag/v3.0.0-alpha-01 - Note the slowness in CSB mode might still be present in this build. Still working on it.

**Comment by chanan** [comment]
Found the reason for the slowness in CSB. Apparently Regex runs REALLY slow on Mono (CSB). Might need to remove the Regex

**Comment by chanan** [comment]
V3.0.0-alpha-04 is out which fixes the slowness of CSB if you want to give it a try.

**Comment by chanan** [comment]
V3.0.0 will be released this weekend.
